Repository procxx/kepka, pull requests merged in 2018-10, with the labels that each got.

#186 Added Doxygen basic support
  Doxyfile
Labels: documentation

#197 Replace mess with maps in lang_auto
  CMakeLists.txt
  Telegram/SourceFiles/codegen/lang/generator.cpp
Labels: enhancement, refactoring

#206 Add raw literals to codegen. Refactor.
  Telegram/SourceFiles/codegen/numbers/generator.cpp
  Telegram/SourceFiles/codegen/style/generator.cpp
Labels: WIP DO NOT MERGE, refactoring

#213 Print diff in clang format
  .travis/build.sh
  modules/clang-cxx-dev-tools.cmake
Labels: category:Infrastructure

#204 Update docker image
  .travis/os_build.sh
  .travis/os_setup.sh
Labels: category:Infrastructure, pr:WIP DO NOT MERGE
